language: python

jobs:
  include:
    - name: "py27 on linux"
      python: "2.7"
      install:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install -e .
        - pip install coveralls
    - name: "py38 on linux"
      python: "3.8"
      install:
        - pip3 install --upgrade pip
        - pip3 install -r requirements.txt
        - pip3 install -e .
        - pip3 install coveralls
    - name: "py3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      install:
        - pip3 install --upgrade pip
        - pip3 install -r requirements.txt
        - pip3 install -e .
        - pip3 install coveralls
    - name: "py3.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      install:
        - pip3 install -r requirements.txt
        - pip3 install -e .
        - pip3 install coveralls
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

script:
  py.test -v --cov=yamldirs .

after_success:
  coveralls
