language: python

sudo: false

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install coveralls

script:
  py.test -v --cov=yamldirs .

after_success:
  coveralls
